### ISSUE TITLE
请问怎么修改添加生词本的默认按键

### ISSUE THREAD

**Issue by Clloz** [wensonsmith/YoudaoTranslator#100]
添加生词本默认是 ctrl + enter，我系统里面设置了这个快捷键是唤出 iterm2，所以我想换一个，但是我修改 action modifier 不生效，请问要怎么修改这个。

**Comment by wensonsmith** [comment]
![Snipaste_2022-01-03_23-41-33](https://user-images.githubusercontent.com/2544185/147950249-69579f03-1403-4d11-b30b-5d5b3e662655.jpg)
