### ISSUE TITLE
M1 芯片运行时错误

### ISSUE THREAD

**Issue by GageChan** [wensonsmith/YoudaoTranslator#101]
错误日志:ERROR: Youdao Translator[Script Filter] Code 126: /Users/gagechan/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/48B18B0C-0527-48D7-9932-2E552FED320E: line 1: ./runtime/txiki: **Bad CPU type in executable**
机型:macbook air m1 2020  
系统:macos12.1 
alfred版本: 4.61
workflow版本:3.0

**Comment by wensonsmith** [comment]
麻烦你按照 txiki readme 尝试一下编译 M1 版本的 tjs https://github.com/saghul/txiki.js

看是否能够编译成功， 等你的好消息

**Comment by GageChan** [comment]
> 我这里没有 M1 芯片设备，麻烦你按照 txiki readme 尝试一下编译 M1 版本的 tjs https://github.com/saghul/txiki.js
> 
> 看是否能够编译成功， 等你的好消息

感谢，我在本地手动编译了一次txiki.js，然后yd就能正常work了

**Comment by wensonsmith** [comment]
麻烦你把M1编译的 txiki 放在此 issue 的附件中吧，可能会有其他人遇到这个问题. thanks

**Comment by Anandonzy** [comment]
我这里cmake安装好了,并且txiki 也编译成功了,插件还是不能使用.

**Comment by GageChan** [comment]
> https://github.com/saghul/txiki.js

在这儿「tjs」https://www.aliyundrive.com/s/dHg5pVhSthu

**Comment by GageChan** [comment]
> 麻烦你把M1编译的 txiki 放在此 issue 的附件中吧，可能会有其他人遇到这个问题. thanks

在这儿「tjs」https://www.aliyundrive.com/s/dHg5pVhSthu

**Comment by Anandonzy** [comment]
下载完如何使用

**Comment by GageChan** [comment]
> 麻烦你把M1编译的 txiki 放在此 issue 的附件中吧，可能会有其他人遇到这个问题. thanks

看看是要这个文件吗？

**Comment by GageChan** [comment]
> 下载完如何使用

改名字，改权限后覆盖到你workflow安装目录下，我的在/Users/gagechan/Library/Application\ Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.89B22C5A-1718-4E6E-9CF4-51C1EF261ACC/runtime/txiki

**Comment by Anandonzy** [comment]
我已经按照您说的操作了,将[tjs]修改权限并且命名为txiki,可是使用yd的时候还报错 
目前您这边如何看的错误日志?感谢~

**Comment by Anandonzy** [comment]
我按照上面说的方式自己编译了一个.
运行 [yd 测试] 显示应用id无效
![image](https://user-images.githubusercontent.com/32696359/148154081-3508c751-7e11-431e-8b63-edf4ab888a96.png)

**Comment by GageChan** [comment]
> 我已经按照您说的操作了,将[tjs]修改权限并且命名为txiki,可是使用yd的时候还报错
> 目前您这边如何看的错误日志?感谢~

在workflow里面有个虫子的图标，点一下，你再输入yd就能看到日志输出了

**Comment by GageChan** [comment]
> 我按照上面说的方式自己编译了一个.
> 运行 [yd 测试] 显示应用id无效
> ![image](https://user-images.githubusercontent.com/32696359/148154081-3508c751-7e11-431e-8b63-edf4ab888a96.png)

那你就是自己的key  secret填错了

**Comment by Anandonzy** [comment]
这个如何填写的呢?

**Comment by GageChan** [comment]
> 这个如何填写的呢?

第一次导入的时候不是让你填写吗？你导入过了就删了重新导入一次，记得填写就好了。好像也可以直接修改，不记得了

**Comment by Anandonzy** [comment]
已经可以了,参见[https://juejin.cn/post/6844903708988276743]
十分感谢~

**Comment by maoxiaoke** [comment]
> > 我这里没有 M1 芯片设备，麻烦你按照 txiki readme 尝试一下编译 M1 版本的 tjs https://github.com/saghul/txiki.js
> > 看是否能够编译成功， 等你的好消息
> 
> 感谢，我在本地手动编译了一次txiki.js，然后yd就能正常work了

worked!

**Comment by kevin1sMe** [comment]
感谢，解决了我的问题，能否打包一个支持M1（arm）的版本呢？

**Comment by yangbisheng** [comment]
我是M1芯片，直接使用TS之前的版本就可以了。

**Comment by iluhcm** [comment]
M2的版本解决方案：
```
brew install cmake autoconf texinfo
git clone --recursive https://github.com/saghul/txiki.js --shallow-submodules && cd txiki.js
make
```
编译出build/tjs 可执行文件，移到
/Users/${user}/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C449B62A-7D0B-4926-A688-CBB29E13F2DE/runtime 修改为txiki 。 新的可执行文件新增了Subcommands，因此需要修改alfred里的workflow代码，将yd里的script filter改为
./runtime/txiki run ./index.js "$1"
