### ISSUE TITLE
Alfred 3 版本支持

### ISSUE THREAD

**Issue by wensonsmith** [wensonsmith/YoudaoTranslator#102]
需要一位在用 Alfred 3 的朋友，帮助我导出一份

**Comment by cassyAnnie** [comment]
你好 我正在使用alfred 3, 目前使用老版本的遇到了如下问题

![image](https://user-images.githubusercontent.com/18167569/148336033-4a71d387-4cdf-47a3-8785-8cab2f681311.png)

![image](https://user-images.githubusercontent.com/18167569/148337028-86633c5a-bded-44a4-867e-4074ae02d41f.png)

**Comment by sqhome-jin** [comment]
谢谢 @wensonsmith 的帮助，已经修复，其他遇到问题的小伙伴，请等待作者上传新的版本，或者使用附件的版本
[Youdao Translate.zip](https://github.com/wensonsmith/YoudaoTranslator/files/7819963/Youdao.Translate.zip)
。

**Comment by wensonsmith** [comment]
@sqhome-jin  thanks , 已加入 release
