### ISSUE TITLE
txiki出错

### ISSUE THREAD

**Issue by wxjer** [wensonsmith/YoudaoTranslator#103]
按照wiki运行了txiki，但是还是报错了。
系统是10.12.6
alfred版本：4.6.1

[11:46:56.799] Logging Started...
[11:46:59.391] Youdao Translator[Script Filter] Queuing argument 'h'
[11:46:59.469] Youdao Translator[Script Filter] Script with argv 'h' finished
[11:46:59.472] ERROR: Youdao Translator[Script Filter] Code 134: dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/wxj/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9D24578D-AEA6-45D1-9A5E-4BFCF856B5A7/./runtime/txiki
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/s/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9D24578D-AEA6-45D1-9A5E-4BFCF856B5A7/./runtime/txiki
  Expected in: /usr/lib/libSystem.B.dylib

/Users/s/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/344607BF-535E-4855-BA0A-795AF8031BA1: line 1:  1681 Abort trap: 6           ./runtime/txiki ./index.js "$1"

**Comment by wensonsmith** [comment]
找到runtime的路径， 然后在 terminal 里直接执行：

/path/to/runtime/txiki -v

试一下能不能正常执行

**Comment by wxjer** [comment]
-v是看版本么？
 输出：v19.0.0-alpha
 还是不行，日志还是上面的那个

**Comment by fuchao2012** [comment]
+1

**Comment by fuchao2012** [comment]
Solved by `run txiki first`
1. find workflow in Alfred
2. right click it  and select `open in Finder`
3. enter folder `runtime`
4. double click `txiki` 
5. open `System Perference > Security & Privacy > General ` 
6. allow `txiki` to run 
7. then you will find alfred is ok to run

**Comment by wxjer** [comment]
把老机器升到了10.15.3后暂无问题
