### ISSUE TITLE
群二维码过期了..支付宝和微信的付款码在国外用不了

### ISSUE THREAD

**Issue by KraftOreo** [wensonsmith/YoudaoTranslator#106]
本来想支持一下，但是人在国外没法用支付宝和微信的付款码。 如下图
![Screenshot_2022-02-06-14-35-19-959_com eg android](https://user-images.githubusercontent.com/38533691/152698305-f2e39142-85d6-430c-a109-2494d07fcf1a.jpg)
![Screenshot_2022-02-06-14-35-44-766_com tencent mm](https://user-images.githubusercontent.com/38533691/152698306-f6c124bd-d2af-4e57-a6e6-8864fe2f4ac2.jpg)

**Comment by wensonsmith** [comment]
哈哈哈， 心意领啦！

群二维码已更新。

**Comment by lightappabc** [comment]
群二维码又过期了
