### ISSUE TITLE
有道智云注册账号过程中，需要登录才能完成注册。

### ISSUE THREAD

**Issue by WickedGod** [wensonsmith/YoudaoTranslator#109]
<img width="469" alt="image" src="https://user-images.githubusercontent.com/16930057/155291755-dd42de9c-d9d5-4c25-9f0d-112b6752684a.png">

**Comment by MoonChasing** [comment]
同遇到，挺离谱的，注册过程需要登录才能进行操作，直接卡死。

**Comment by MoonChasing** [comment]
同遇到，挺离谱的，注册过程需要登录才能进行操作，直接卡死。

**Comment by wensonsmith** [comment]
与插件无关
