### ISSUE TITLE
功能建议：翻译长文本换行，以及翻译结果cache

### ISSUE THREAD

**Issue by chenjh16** [wensonsmith/YoudaoTranslator#74]
1. 翻译长文本换行。有时选择的句子过长，翻译的结果Alfred一行显示不全，需要回车复制后查看，不太方便。建议判断一下文本长度，对翻译结果进行多行分割，然后使用多个Alfred item来显示翻译结果。
2. 建议使用cache来缓存单词和词组的联网翻译结果，从而加速重复查询速度。可以加一个自定义变量来开启或关闭cache。

**Comment by wensonsmith** [comment]
翻译结果，60 汉字以内翻译过长已折叠至副标题

cache 增加了复杂度，收益不高

**Comment by kk17** [comment]
用了3.1版本，翻译还是显示不全。
![image](https://user-images.githubusercontent.com/3477852/222971344-41866516-b697-4ba4-a774-485aeb10795e.png)
![image](https://user-images.githubusercontent.com/3477852/222971353-a23e824f-66dc-4e10-96b6-bcba249bcae4.png)

**Comment by xbpk3t** [comment]
DITTO
