### ISSUE TITLE
YoudaoTranslate 3.0 版本

### ISSUE THREAD

**Issue by wensonsmith** [wensonsmith/YoudaoTranslator#90]
1. 虽然PHP是世界上最好的语言，依然要使用 TypeScript 进行重构，使用 [esno](https://github.com/antfu/esno) 作为 runtime
2. 把翻译服务抽象化，提供默认的有道翻译的 adapter， 后期可以再开发baidu翻译等其他的adapter（#88， #78 ）
3. 完善生词本的功能，生词本默认需要添加一个同名的生词本才可以正常同步，这次把这个问题修复(#56)
4. 长句换行功能需求，不会进行换行展示，这样太丑了，一点都不优雅，把超出部分放在 sub title 内感觉会好些 (#58, #74)

**Comment by wensonsmith** [comment]
定在 11 月 11 发版

Deadline 就是生产力！

**Comment by yimao** [comment]
加油⛽️

**Comment by TheBeacon1** [comment]
加油！！

**Comment by osaka2020** [comment]
加油！ 支持！

**Comment by hronro** [comment]
支持！如果 11 月 11 号能更新的话我就不装 PHP 环境去用旧版了 (macOS 12)，毕竟平时不会用到 PHP。

另外有个疑问，按照我的理解，esno 只是一个把 TS 翻译成 JS 的 Node.js 插件，最后还是要依赖 Node.js 来执行的，似乎并不能达成[这里](https://github.com/wensonsmith/YoudaoTranslate/issues/87#issuecomment-954401890)提到的「可以直接执行，不再依赖php或python」。

如果一定要用 TS 又不希望插件有什么 runtime 的依赖的话，倒是可以考虑用 quickjs 这种这种轻量级的 runtime，直接把 quickjs 打包到插件里一起发布。

**Comment by wensonsmith** [comment]
@hronro 

你是对的，我理解错了。esno 还得安装 node 才能使用。

目标是不依赖系统的环境，我去研究一下 quickjs 

thanks a lot !

**Comment by wensonsmith** [comment]
找到了[deno](https://github.com/denoland/deno)， 提供二进制包，可以直接执行 Ts,  所以方案为打包 deno 作为 runtime

**Comment by hronro** [comment]
@wensonsmith Deno 也太大了吧，我印象中 Deno 写个 Hello World 也有 40MB+ 了

**Comment by wensonsmith** [comment]
@hronro 

是有点大，昨天下了 deno 的二进制包， 26M

现在蚌埠住了，不然就需要依赖 node 环境， 现在学 go 还来不来的及。。

quickjs 没有找到 macos 的二进制包，只有 linux 和 win 的

**Comment by hronro** [comment]
@wensonsmith 
quickjs 是支持 macOS 的，quickjs 全 C 写的，你自己编译的话也很简单的。如果你用 Homebrew 的话也可以直接 `brew install quickjs`。

另外可以考虑下 macOS 自带的 JavaScriptCore，这样可以白嫖 OS 的 JS runtime: https://developer.apple.com/documentation/javascriptcore

我自己试了下用 C 包一层，感觉是可以的：

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/15059605/141046434-bbc8499d-6500-4535-b30e-cd9adaef6c99.png">

**Comment by zthxxx** [comment]
deanline 还来得及么

**Comment by TheBeacon1** [comment]
估计够呛了，我今天等了一天，应该是作者太忙了，加油！！！

**Comment by wensonsmith** [comment]
@zthxxx @TheBeacon1 

赶不及了.. T ^ T

想要实现自带 runtime 比我预想的复杂啊

quickjs (788K) 得自己封装 fetch，封装到一半然后发现了带 fetch 的 [txiki](https://github.com/saghul/txiki.js) (1.8M)

现在决定先用 txiki 实现功能，后面再封装 fetch 切到 quickjs

目前运行环境和请求已经没问题，正在用 Ts 封装 PHP 里面的那个 workflow 包

还得再等等 = =

**Comment by duhongliang** [comment]
> @zthxxx @TheBeacon1
> 
> 赶不及了.. T ^ T
> 
> 想要实现自带 runtime 比我预想的复杂啊
> 
> quickjs (788K) 得自己封装 fetch，封装到一半然后发现了带 fetch 的 [txiki](https://github.com/saghul/txiki.js) (1.8M)
> 
> 现在决定先用 txiki 实现功能，后面再封装 fetch 切到 quickjs
> 
> 目前运行环境和请求已经没问题，正在用 Ts 封装 PHP 里面的那个 workflow 包
> 
> 还得再等等 = =

辛苦

**Comment by chengcyber** [comment]
一个小建议：先发一个 TS 实现编译到 JS 依赖 node 的 3.0. JS 社区 workflow 可以看看这个 https://www.npmjs.com/package/alfy

**Comment by yimao** [comment]
> > @zthxxx @TheBeacon1
> > 赶不及了.. T ^ T
> > 想要实现自带 runtime 比我预想的复杂啊
> > quickjs (788K) 得自己封装 fetch，封装到一半然后发现了带 fetch 的 [txiki](https://github.com/saghul/txiki.js) (1.8M)
> > 现在决定先用 txiki 实现功能，后面再封装 fetch 切到 quickjs
> > 目前运行环境和请求已经没问题，正在用 Ts 封装 PHP 里面的那个 workflow 包
> > 还得再等等 = =
> 
> 辛苦 没有打赏的地方，这个值得一个打赏。

还真有，在 readme 里 😄

**Comment by linbo0518** [comment]
加油!

**Comment by zthxxx** [comment]
现在学 go 还来得及 🌝

**Comment by zthxxx** [comment]
但 go 的二进制也是需要不同版本做分发的

**Comment by wensonsmith** [comment]
整体框架已经搭好， 周末应该可以来一个 alpha 啦

然后感叹一句，当我还在纠结学不学 go，  Copilot 已经要淘汰我了 😅 

<img width="570" alt="image" src="https://user-images.githubusercontent.com/2544185/141494839-e31bcca9-3876-4e25-9760-710b9b09d4ae.png">

<img width="422" alt="image" src="https://user-images.githubusercontent.com/2544185/141495597-aa44d2fb-2f86-4df4-82fe-866c9ac0d2c7.png">

**Comment by LucasZhan** [comment]
加油，冲冲冲

**Comment by tian3180** [comment]
这周有希望不🙋‍♂️

**Comment by wensonsmith** [comment]
@tian3180 

必须的， Youdao 的翻译已经做好了， 我整理下代码，晚上发一版

**Comment by wensonsmith** [comment]
第一版终于发布， macOS Monterey 的各位可以不用安装 PHP 啦

暂时还不支持单词本和百度API，如果有单词本的需求，还需要使用 V2

百度API的适配欢迎 PR

**Comment by duhongliang** [comment]
> 第一版终于发布， macOS Monterey 的各位可以不用安装 PHP 啦
> 
> 暂时还不支持单词本和百度API，如果有单词本的需求，还需要使用 V2
> 
> 百度API的适配欢迎 PR

弱弱的问一句怎么安装呢

**Comment by GreatAuk** [comment]
@wensonsmith 打包有问题吗，没有 workflow 文件
![image](https://user-images.githubusercontent.com/20253809/141728479-40341441-3ffc-4692-a730-04d5e4fafd0b.png)

**Comment by wensonsmith** [comment]
@GreatAuk 

现在有了，昨晚上传失败了，我没发现

**Comment by GreatAuk** [comment]
@wensonsmith 差一个 logo 
![image](https://user-images.githubusercontent.com/20253809/141737251-6a3870ef-01ab-46b4-b7ee-065f682a0f0a.png)

**Comment by wensonsmith** [comment]
> @wensonsmith 差一个 logo ![image](https://user-images.githubusercontent.com/20253809/141737251-6a3870ef-01ab-46b4-b7ee-065f682a0f0a.png)

加上啦

**Comment by lyfoppa** [comment]
我把之前的四条配置全都复制了过来，但是没法翻译
<img width="572" alt="截屏2021-11-15 下午4 20 06" src="https://user-images.githubusercontent.com/35186585/141746593-6b14d7a4-7a85-4940-9cd1-a76bb1813301.png">

**Comment by wensonsmith** [comment]
@lyfoppa 

不用全复制过来，原来的配置字段名称和现在也不一样

只需要填上 key （youdao_appKey） 和secret (youdao_secret) 就可以

你这个什么也没提示，有点奇怪

**Comment by wensonsmith** [comment]
感觉我得建一个微信群啊， 有问题直接群里沟通会方便许多

**Comment by duhongliang** [comment]
> 感觉我得建一个微信群啊， 有问题直接群里沟通会方便许多

是的，需要建一个群，方便很多，打赏也更方便，😝

**Comment by wensonsmith** [comment]
@duhongliang 

已经在不起眼的地方加上了微信群的二维码 😆

**Comment by duhongliang** [comment]
> @duhongliang
> 
> 已经在不起眼的地方加上了微信群的二维码 😆

已打赏

**Comment by akiakise** [comment]
runtime 中附带的 txiki 在首次使用 workflow 时不能正常启动，原因是 Mac 默认有安全策略，https://support.apple.com/zh-cn/guide/mac-help/mh40616/mac。
解决方案是从 workflow 找到实际的安装目录（右键 workflow 并点击 Open in Finder），然后打开 runtime 文件夹，按住 ctrl 点击 txiki，打开一次。打开成功后直接关掉终端即可，后续就可以正常使用啦 🎉🎉🎉。

建议补充下说明。

**Comment by wensonsmith** [comment]
@akiakise thanks

已在readme中加上

**Comment by duhongliang** [comment]
> 

二维码过期了

**Comment by hu-zhi-hang** [comment]
![image](https://user-images.githubusercontent.com/8455958/146717510-a5bb797c-d950-40a3-8873-95999375f68d.png)
只支持 Alfred 4 ？

**Comment by wensonsmith** [comment]
除单词本其他功能均已完成

**Comment by airshu** [comment]
> 除单词本其他功能均已完成

期待单词本功能

**Comment by AaronWang** [comment]
长句自动换行不能用，Alfred版本 4.0.4
