### ISSUE TITLE
功能建议：Enter/Shift Enter 打开有道词典网页版

### ISSUE THREAD

**Issue by chengjianhua** [wensonsmith/YoudaoTranslator#97]
当 Enter 或者 Shift + Enter 的时候，是否可以打开有道词典的 Web 网页，例如像这样的链接：http://dict.youdao.com/search?q=irritant。这样可以方便地在网页里查看更丰富的解释，例如同义词等。

**Comment by wensonsmith** [comment]
是的， v2 按 shift 可以预览， v3 的还没加，这个可以支持的

**Comment by chengjianhua** [comment]
> 是的， v2 按 shift 可以预览， v3 的还没加，这个可以支持的

@wensonsmith 是的，发现了……请问 v3 计划啥时候支持呢？已经在用 v3 了，插件很棒~🎉

**Comment by Neptune10000** [comment]
单词本和shift预览功能都超有用，期待更新🤩🥳

**Comment by wensonsmith** [comment]
3.1 已支持

**Comment by fatedier** [comment]
@wensonsmith Hi，想问下 shift 预览功能有没有什么方法可以关闭呢？因为 shift 被我用于输入法的中英文切换，习惯输入完之后就按一下 shift，总是会误操作。

**Comment by wensonsmith** [comment]
@fatedier 

![image](https://user-images.githubusercontent.com/2544185/148981315-deda3fc4-a113-4835-b738-40617c152d04.png)

**Comment by fatedier** [comment]
@wensonsmith Great, thanks!
